DROP TABLE IF EXISTS TOP50GLOBAL;

CREATE TABLE  "TOP50GLOBAL" (
    "ID" NUMBER NOT NULL PRIMARY KEY,
	"NOMBRE" VARCHAR2(100) ,
	"ARTISTA" VARCHAR2(100),
	"ALBUM" VARCHAR2(100),
	"LONGITUD" NUMBER(8)

);