INSERT INTO TOP50GLOBAL VALUES ('0','United In Grief','Kendrick Lamar','Mr.Morale & The Big Steppers','196');
INSERT INTO TOP50GLOBAL VALUES ('1','As It Was','Harry Styles','As It Was','167');
INSERT INTO TOP50GLOBAL VALUES ('2','Moscow Mule','Bad Bunny','Un Verano Sin Ti','246');
INSERT INTO TOP50GLOBAL VALUES ('3','We Cry Together','Kendrick Lamar','Mr.Morale & The Big Steppers','202');
INSERT INTO TOP50GLOBAL VALUES ('4','Ojitos Lindos','Bad Bunny','Un Verano Sin Ti','258');
INSERT INTO TOP50GLOBAL VALUES ('5','Me Porto Bonito','Bad Bunny','Un Verano Sin Ti','179');
INSERT INTO TOP50GLOBAL VALUES ('6','First Class','Jack Harlow','Come Home The Kids Miss You','174');
INSERT INTO TOP50GLOBAL VALUES ('7','Tití Me Preguntó','Bad Bunny','Un Verano Sin Ti','244');
INSERT INTO TOP50GLOBAL VALUES ('8','Party','Bad Bunny','Un Verano Sin Ti','228');
INSERT INTO TOP50GLOBAL VALUES ('9','Crown','Kendrick Lamar','Mr.Morale & The Big Steppers','264');
INSERT INTO TOP50GLOBAL VALUES ('10','About Damn Time','Lizzo','About Damn Time','192');
INSERT INTO TOP50GLOBAL VALUES ('11','PROVENZA','KAROL G','PROVENZA','210');
INSERT INTO TOP50GLOBAL VALUES ('12','Un Ratito','Bad Bunny','Un Verano Sin Ti','228');
INSERT INTO TOP50GLOBAL VALUES ('13','Después de la Playa','Bad Bunny','Un Verano Sin Ti','230');
INSERT INTO TOP50GLOBAL VALUES ('14','Tarot','Bad Bunny','Un Verano Sin Ti','238');
INSERT INTO TOP50GLOBAL VALUES ('15','Neverita','Bad Bunny','Un Verano Sin Ti','213');
INSERT INTO TOP50GLOBAL VALUES ('16','Una Noche en Medellín','Cris Mj','Una Noche en Medellín','234');
INSERT INTO TOP50GLOBAL VALUES ('17','MAMIII','Becky G & KAROL G','ESQUEMAS','216');
INSERT INTO TOP50GLOBAL VALUES ('18','Dos Mil 16','Bad Bunny','Un Verano Sin Ti','208');
INSERT INTO TOP50GLOBAL VALUES ('19','Un Coco','Bad Bunny','Un Verano Sin Ti','226');
INSERT INTO TOP50GLOBAL VALUES ('20','WAIT FOR U','Future','I NEVER LIKED YOU','190');
INSERT INTO TOP50GLOBAL VALUES ('21','Another Love','Tom Odell','Another Love','318');
INSERT INTO TOP50GLOBAL VALUES ('22','B11','Rvssian','B11 feat Myke Towers','198');
INSERT INTO TOP50GLOBAL VALUES ('23','Take Me Home','John Denver','Poems','190');
INSERT INTO TOP50GLOBAL VALUES ('24','Billie Jean','Michael Jackson','Thriller','294');
INSERT INTO TOP50GLOBAL VALUES ('25','Ahora Y Siempre','Quevedo','Ahora Y Siempre','159');
INSERT INTO TOP50GLOBAL VALUES ('26','Netflixxx','Brytiago','Netflixxx','217');
INSERT INTO TOP50GLOBAL VALUES ('27','Música Ligera','Ana Mena','Música Ligera','240');
INSERT INTO TOP50GLOBAL VALUES ('28','Voy a Celebrarlo','Lágrimas de Sangre','Si uno no se rinde','393');
INSERT INTO TOP50GLOBAL VALUES ('29','Mirando al cielo','Huecco','Assalto','236');
INSERT INTO TOP50GLOBAL VALUES ('30','Tú','Sergio Dalma','Vía Dalma','244');
INSERT INTO TOP50GLOBAL VALUES ('31','I Wanna Go','Britney Spears','Femme Fatale','190');
INSERT INTO TOP50GLOBAL VALUES ('32','Flecha','Leiva','Cuando Te Muerdes el Labio','228');
INSERT INTO TOP50GLOBAL VALUES ('33','Piel de Cordero','Quevedo','Piel de Cordero','212');
INSERT INTO TOP50GLOBAL VALUES ('34','Numero 1','Oscu','Numero 1','154');
INSERT INTO TOP50GLOBAL VALUES ('35','Pantysito','Alejo','Pantysito','240');
INSERT INTO TOP50GLOBAL VALUES ('36','Cayó la Noche','La Pantera','Cayó la Noche','486');
INSERT INTO TOP50GLOBAL VALUES ('37','Mi Luz','Rvfv','NASTU','168');
INSERT INTO TOP50GLOBAL VALUES ('38','Jordan','Ryan Castro','Jordan','176');
INSERT INTO TOP50GLOBAL VALUES ('39','Desesperados','Rauw Alejandro','VICE VERSA','215');
INSERT INTO TOP50GLOBAL VALUES ('40','Sigue','Beny Jr','Capítulo 1','205');
INSERT INTO TOP50GLOBAL VALUES ('41','ULTRA SOLO','Polimá Westcoast','ULTRA SOLO','245');
INSERT INTO TOP50GLOBAL VALUES ('42','RUMBATÓN','Daddy Yankee','LEGENDADDY','249');
INSERT INTO TOP50GLOBAL VALUES ('43','Tacones Rojos','Sebastian Yatra','Dharma','189');
INSERT INTO TOP50GLOBAL VALUES ('44','Andrea','Bad Bunny','Un Verano Sin Ti','211');
INSERT INTO TOP50GLOBAL VALUES ('45','Fuera del mercado','Ocean','Dannocean','160');
INSERT INTO TOP50GLOBAL VALUES ('46','MEMORIAS','Mora','MICRODOSIS','174');
INSERT INTO TOP50GLOBAL VALUES ('47','Chamaquita','Quevedo','Chamaquita','192');
INSERT INTO TOP50GLOBAL VALUES ('48','Mon Amour','Zzoilo','Mon Amour','180');
INSERT INTO TOP50GLOBAL VALUES ('49','Plan A','Paulo Londra','Plan A','168');



